# Agent Builder Configuration
# Defines rules, mappings, and thresholds for agent generation

compression:
  # Target character limits by tier
  limits:
    green: 200
    yellow: 300
    red: 400
  
  # Symbol mappings for compression
  symbols:
    workflow_arrow: "→"
    transform: "⇒"
    and: "&"
    or: "|"
    therefore: "∴"
    because: "∵"

# Tool permission mappings by agent type
tool_mappings:
  # Simple agents (Green tier)
  reader:
    tools: [Read]
    confidence: 0.95
  writer:
    tools: [Write]
    confidence: 0.95
  executor:
    tools: [Bash]
    confidence: 0.90
  
  # Standard agents (Yellow tier)
  developer:
    tools: [Read, Write, Edit, Bash, Grep]
    confidence: 0.85
  debugger:
    tools: [Read, Edit, Bash, Grep, Glob]
    confidence: 0.85
  tester:
    tools: [Read, Bash, Write]
    confidence: 0.80
  
  # Complex agents (Red tier)
  orchestrator:
    tools: [Read, Write, Edit, Bash, Grep, Glob, Task, TodoWrite]
    confidence: 0.75
  architect:
    tools: [Read, Write, Task, mcp__sequential-thinking__sequentialthinking]
    confidence: 0.70

# Complexity assessment thresholds
complexity:
  green:
    max_tools: 3
    max_workflow_steps: 3
    domains: 1
  yellow:
    max_tools: 6
    max_workflow_steps: 5
    domains: 2
  red:
    max_tools: 10
    max_workflow_steps: 8
    domains: 3

# Quality thresholds
quality:
  min_description_length: 20
  max_description_length: 200
  required_fields:
    - name
    - description
    - tools
  performance_targets:
    initialization_ms: 100
    character_limit: 400

# Activation patterns
activation_patterns:
  proactive_keywords:
    - "use proactively"
    - "auto-activates"
    - "automatically"
  trigger_verbs:
    - "create"
    - "build"
    - "generate"
    - "analyze"
    - "debug"
    - "test"
    - "deploy"
    - "optimize"

# Validation rules
validation:
  name_pattern: "^[a-z][a-z0-9-]*$"
  max_name_length: 30
  forbidden_names:
    - "agent"
    - "claude"
    - "assistant"
    - "system"
  
# Batch creation settings
batch:
  max_agents_per_batch: 20
  naming_pattern: "{{base}}-{{variant}}"
  variant_separator: "-"

# Template selection rules
template_selection:
  criteria:
    - complexity_score
    - domain_match
    - tool_requirements
  fallback: "templates/yellow/developer.yaml"